### ISSUE TITLE
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

### ISSUE THREAD

**Issue by gxggsrmyy** [suconghou/dlna-python#1]
@suconghou 请教一下,运行出错,是什么原因,
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Downloads\dlna-python-master\dlna-python-master\main.py", line 811, in run
    self.run()
  File "C:\Users\Administrator\Downloads\dlna-python-master\dlna-python-master\main.py", line 859, in run
    self.listen()
  File "C:\Users\Administrator\Downloads\dlna-python-master\dlna-python-master\main.py", line 819, in listen
    self.search("ssdp:all")
  File "C:\Users\Administrator\Downloads\dlna-python-master\dlna-python-master\main.py", line 883, in search
    s.bind(('239.255.255.250', 1900))
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
    self.sendUdp(text)
  File "C:\Users\Administrator\Downloads\dlna-python-master\dlna-python-master\main.py", line 871, in sendUdp
    data, address = udp_socket.recvfrom(2048, 0x40)
OSError: [WinError 10045] 参考的对象类型不支持尝试的操作。
Starting server, listen at: 192.168.7.123:8888

**Comment by gxggsrmyy** [comment]
@suconghou 运行macast 这个类似项目,地址也是'239.255.255.250', 1900, 能正常运行,

**Comment by suconghou** [comment]
@gxggsrmyy  问题已修复,可下载新源码重试

**Comment by gxggsrmyy** [comment]
https://2bb7cdd20f19f6c36309fac623b206e4.v.smtcdns.net/tlivecloud-cdn.ysp.cctv.cn/A6229A879CF68A3D5992BECDC53CB77E498510BD8A463DFCDF8671914227711F486CDD52B0614DD236C6567B72C4F7913D11D8032038AA8890030CB03A331B92846D5C00664706166BC6AA4F097E62380BBB5DFA792C76B50A854A4B7088F571A8E73C9575B0DD9806ACAE00BF596809B435C4F3652DEDD7BC58808707FEB318165CCAA651EA7FC73C5C4CC213EADDDC/2000205103.m3u8?from=player&svrtime=1636124275&pid=600001818&cdn=5501&revoi=88A55A1B9EF5FE26EF015A17EBD9D88FF57E1A02C17F8AF1FCB6180C2C46D3AC

@suconghou 同样的网址， 有时可以投屏成功，有时提示 请输入正确的url地址

**Comment by gxggsrmyy** [comment]
@suconghou 另外，怎样作为服务端接受投屏？

**Comment by gxggsrmyy** [comment]
@suconghou 

urllib.error.HTTPError: HTTP Error 500: Internal Server Error
192.168.66.200 - - [06/Nov/2021 10:37:49] code 500, message HTTP Error 500: Internal Server Error
192.168.66.200 - - [06/Nov/2021 10:37:49] "POST /play?url=http://192.168.66.187:1063/&playUrl=https://1abc11c763d635517e69f5da95e63c9a.v.smtcdns.net/tlivecloud-cdn.ysp.cctv.cn/D86DEC72D262CE7BED448A3289B83C39D2F3354321CB86A3C2EA056D431BEDDA69D8E90E0E6846360919E6592312887E46E18E3D6620E690BEEE3C35786B6DC9D23563F42D1A52E2A3D1723F869D35EDC484508F0B518D9AF353CB39250FB98B91BEBEAC20C2D80E06686D53EF728F5E3046B68E9FC32931655ACC3446D24B4B0415F5158181D5FC0A3177FFDD986F99/2000204503.m3u8?from=player&svrtime=1636166090&pid=600001817&cdn=5501&revoi=F8FC50C7A9B85D73C2C6FB0BAB5CAEB1ED4BF87E9CFF87C6F09155CE291443C6 HTTP/1.1" 500 -

**Comment by gxggsrmyy** [comment]
@suconghou 播放地址有中文就出错

urllib.error.HTTPError: HTTP Error 500: Internal Server Error
192.168.66.200 - - [06/Nov/2021 11:12:29] code 500, message HTTP Error 500: Internal Server Error
192.168.66.200 - - [06/Nov/2021 11:12:29] "POST /play?url=http://192.168.66.187:1063/&playUrl=http://192.168.66.200:8000/mp4%20-%20%E5%89%AF%E6%9C%AC.mp4 HTTP/1.1" 500 -

**Comment by suconghou** [comment]
@gxggsrmyy  同一局域网内,多搜索一会就有,校验问题已修改,中文的问题未复现,可以试试新的代码.

**Comment by gxggsrmyy** [comment]
@suconghou 
http://192.168.1.62/洪恩识字04.mp4    类似这种带中文的不能投屏
（同一局域网内,多搜索一会就有），还是搜不到服务端

**Comment by gxggsrmyy** [comment]
@suconghou 一直探测中...,搜不到设备

**Comment by gxggsrmyy** [comment]
@suconghou 就算网页上搜到自身的服务, 手机 爱奇艺上也搜不到电脑服务端, 已经是同一网段.

**Comment by gxggsrmyy** [comment]
@suconghou 你好, 程序设计很巧妙, 想问一下为什么 程序自身客户端 发现不了自身 服务端?

**Comment by suconghou** [comment]
@gxggsrmyy  之前的版本可以，是我故意禁用掉了， 参考 https://github.com/suconghou/dlna-python/commit/a4e1cf86bd9dd06c45277a5466928cb706fdfd5b  IP_MULTICAST_LOOP 配置

**Comment by gxggsrmyy** [comment]
@suconghou 非常感谢答复
